### ISSUE TITLE
New title 

### ISSUE THREAD

**Issue by beast56782** [zelalemgetahun9374/USGS-Lidar-custom-package#10]
I'm not sure about applying the changes in base.rb. I'm not really convinced that Errno::ECONNRESET can be univocally mapped as a ResponseIncomplete error.

Also, there's no way in the Record to know whether the response was successful or not. This can be a problem because some parsers expects a specific response format. So we need to instruct all the parsers to understand an incomplete response

**Comment by zelalemgetahun9374** [comment]
This comment has no connection with this project. Therefore, I have closed the issue.
